name: noise_tool
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-401.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: NeueMachina
      fonts:
        - asset: assets/fonts/NeueMachina-Regular.ttf
        - asset: assets/fonts/NeueMachina-Ultralight.ttf
          weight: 100
        - asset: assets/fonts/NeueMachina-Medium.ttf
          weight: 500
        - asset: assets/fonts/NeueMachina-Bold.ttf
          weight: 700
        - asset: assets/fonts/NeueMachina-UltraBold.ttf
          weight: 900
